# Generated by Django 4.1.7 on 2023-06-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VisuDados', '0003_alter_data_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='dado',
            new_name='concentracao',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='dado2',
            new_name='naosei',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='label',
            new_name='temperatura',
        ),
    ]
