# Generated by Django 4.1.7 on 2023-06-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VisuDados', '0004_rename_dado_data_concentracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='naosei',
        ),
    ]
